---
# template-gh-lint: 1.2.0
name: "Lint/X_TARGET_TITLE_X"

env:
  DEV_CICD_DEBUG: "NONE"
  BL64_LIB_CICD: "YES"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"

jobs:
  lint-X_TARGET_X:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          # X_TOOLS_PLACEHOLDER_X

      # - name: "Prepare for linting"
      #   run : "X_BUILD_PLACEHOLDER_X"

      - name: "Run Linter"
        run: "X_PLACEHOLDER_3_X"
...
