---
# template: 2.4.0
name: "Test/Bash"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: "NONE"
  BL64_LIB_CICD: "YES"
  DEV_TEST_BASH_RUNNER_ENVIRONMENT: "ON"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "test/bash/**"

jobs:
  test-bash-linux:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        target:
          - "ALP"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache local tools"
        uses: "actions/cache@v4"
        with:
          path: ./lib
          key: ${{ runner.os }}-lib-cache
          restore-keys: |
            ${{ runner.os }}-lib-cache

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base

      - name: "Prepare for testing"
        run: "./bin/dev-prep-project"

      - name: "Run Unix generic tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash $DEV_TEST_BASH_CONTAINER_${{matrix.target}} ${DEV_TEST_BASH_CASES}/UNX

  test-bash-macos:
    runs-on: "macos-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Upgrade Bash version"
        run: |
          ./bin/dev-lib-bash

      - name: "Cache local tools"
        uses: "actions/cache@v4"
        with:
          path: ./lib
          key: ${{ runner.os }}-lib-cache
          restore-keys: |
            ${{ runner.os }}-lib-cache

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base

      - name: "Prepare for testing"
        run: "./bin/dev-prep-project"

      - name: "Run Unix generic tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash-host ${DEV_TEST_BASH_CASES}/UNX
